-- MySQL Script generated by MySQL Workbench
-- Sun Nov 30 17:20:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mensaje
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mensaje` ;

-- -----------------------------------------------------
-- Schema mensaje
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mensaje` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mensaje` ;

-- -----------------------------------------------------
-- Table `mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mensaje` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mensaje` (
  `id_mensaje` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `texto` TINYTEXT NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id_mensaje`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idmensaje_UNIQUE` ON `mensaje` (`id_mensaje` ASC) ;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

